name: Website acceptance tests
on:
  workflow_dispatch: {}
  workflow_run:
      workflows:
      - Unity CI CD Pipeline
      - Virtual Arcade Bar Website
      types:
        - completed

jobs:
  websiteAcceptanceTests:
    name: Run acceptance tests on website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm --prefix ./acceptance-tests install
      - run: npm --prefix ./acceptance-tests run test-stage
      - run: npm --prefix ./acceptance-tests run test-production
